### YamlMime:OData
uid: Microsoft.Dynamics.CRM.ApiSettings
name: "ApiSettings"
type: solution
metadata: 
  title: "Common Data Service and Dynamics 365 Customer Engagement ApiSettings Solution Reference | MicrosoftDocs"
  ms.date: "05/03/2020"
  ms.service: "crm-online"
  ms.topic: "reference"
  ms.assetid: 5f7411a2-75ca-4964-bbbb-e3dbaff9b31b
  author: "KumarVivek"
  ms.author: "kvivek"
  manager: "Annbe"
  meta-description: "Reference information about the Dynamics 365 Customer Engagement ApiSettings Solution."
namespace: Microsoft.Dynamics.CRM
header:
# This solution has no description.
 unique_name: ApiSettings
 version: "1.0.0.13"
 customization_prefix: 
# This solution includes no entities.
# This solution includes no actions.
# This solution has no remarks.
href_see_also:
- text: "Use the Common Data Service Web API"
  href: "https://docs.microsoft.com/powerapps/developer/common-data-service/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex