### YamlMime:OData
uid: Microsoft.Dynamics.CRM.msdyn_ImageConfiguration
name: "Image Configuration"
type: solution
metadata: 
  title: "Common Data Service and Dynamics 365 Customer Engagement Image Configuration Solution Reference | MicrosoftDocs"
  ms.date: "04/27/2020"
  ms.service: "crm-online"
  ms.topic: "reference"
  ms.assetid: fd6c98df-b7ef-4188-9b38-f74612944d07
  author: "KumarVivek"
  ms.author: "kvivek"
  manager: "Annbe"
  meta-description: "Reference information about the Dynamics 365 Customer Engagement Image Configuration Solution."
namespace: Microsoft.Dynamics.CRM
header:
# This solution has no description.
 unique_name: msdyn_ImageConfiguration
 version: "1.0.0.6"
 customization_prefix: 
# This solution includes no entities.
# This solution includes no actions.
# This solution has no remarks.
href_see_also:
- text: "Use the Common Data Service Web API"
  href: "https://docs.microsoft.com/powerapps/developer/common-data-service/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex