### YamlMime:OData
uid: Microsoft.Dynamics.CRM.CascadeConfiguration
name: "CascadeConfiguration"
type: complextype
metadata: 
  title: "Microsoft Dynamics 365 Customer Engagement CascadeConfiguration ComplexType Reference | MicrosoftDocs"
  ms.date: "2017-09-15"
  ms.service: "crm-online"
  ms.topic: "reference"
  applies_to: 
    - "Dynamics 365 (online)"
  ms.assetid: 970becb8-0f4d-4b7a-922e-cf73d4166b0b
  author: "jimdaly"
  ms.author: "jdaly"
  manager: "jdaly"
  meta-description: "Reference information about the Dynamics 365 Customer Engagement Web API CascadeConfiguration ComplexType."
namespace: Microsoft.Dynamics.CRM
# This complex type doesn't inherit from another complextype.
description: "Contains properties representing actions that may be performed on the referenced entity in a one-to-many entity relationship." 
properties:
  description: "The properties of a complex type contain the structured data of the type."
  property_items:
  - name: Assign
    type: Microsoft.Dynamics.CRM.CascadeType
    nullable: true
    unicode: true
    description: "The referenced entity record owner is changed. "
    iscollection: false
  - name: Delete
    type: Microsoft.Dynamics.CRM.CascadeType
    nullable: true
    unicode: true
    description: "The referenced entity record is deleted."
    iscollection: false
  - name: Merge
    type: Microsoft.Dynamics.CRM.CascadeType
    nullable: true
    unicode: true
    description: "The record is merged with another record."
    iscollection: false
  - name: Reparent
    type: Microsoft.Dynamics.CRM.CascadeType
    nullable: true
    unicode: true
    description: "The referencing attribute in a parental relationship changes "
    iscollection: false
  - name: Share
    type: Microsoft.Dynamics.CRM.CascadeType
    nullable: true
    unicode: true
    description: "The referenced entity record is shared with another user. "
    iscollection: false
  - name: Unshare
    type: Microsoft.Dynamics.CRM.CascadeType
    nullable: true
    unicode: true
    description: "Sharing is removed for the referenced entity record. "
    iscollection: false
  - name: RollupView
    type: Microsoft.Dynamics.CRM.CascadeType
    nullable: true
    unicode: true
    description: "Indicates that the associated activities of the related entity should be included in Activity Associated View for the primary entity."
    iscollection: false
# This complex type doesn't have any navigation properties.
usedby:
  description: "The following use the CascadeConfiguration ComplexType."
  usedby_items:
  - name: Microsoft.Dynamics.CRM.OneToManyRelationshipMetadata
    used_as: Property
  - name: Microsoft.Dynamics.CRM.ComplexOneToManyRelationshipMetadata
    used_as: Property
# There are no remarks for this complex type.
href_see_also:
- text: "Use the Microsoft Dynamics CRM Web API"
  href: "https://docs.microsoft.com/dynamics365/customer-engagement/developer/use-microsoft-dynamics-365-web-api"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex
