### YamlMime:OData
uid: Microsoft.Dynamics.CRM.GetDistinctValuesImportFileResponse
name: "GetDistinctValuesImportFileResponse"
type: complextype
metadata: 
  title: "Microsoft Dynamics 365 Customer Engagement GetDistinctValuesImportFileResponse ComplexType Reference | MicrosoftDocs"
  ms.date: "10/20/2017"
  ms.service: "crm-online"
  ms.topic: "reference"
  applies_to: 
    - "Dynamics 365 (online)"
  ms.assetid: 11dfbbc6-4e70-4c72-b546-883831747046
  author: "jimdaly"
  ms.author: "jdaly"
  manager: "jdaly"
  meta-description: "Reference information about the Dynamics 365 Customer Engagement Web API GetDistinctValuesImportFileResponse ComplexType."
namespace: Microsoft.Dynamics.CRM
# This complex type doesn't inherit from another complextype.
description: "The response from the GetDistinctValuesImportFile function. " 
properties:
  description: "The properties of a complex type contain the structured data of the type."
  property_items:
  - name: Values
    type: Edm.String
    nullable: false
    unicode: false
    description: "The distinct values for a column in the source file. "
    iscollection: true
# This complex type doesn't have any navigation properties.
usedby:
  description: "The following use the GetDistinctValuesImportFileResponse ComplexType."
  usedby_items:
  - name: Microsoft.Dynamics.CRM.GetDistinctValuesImportFile
    used_as: ReturnType
# This complex type has no remarks.
href_see_also:
- text: "Use the Microsoft Dynamics CRM Web API"
  href: "https://docs.microsoft.com/dynamics365/customer-engagement/developer/use-microsoft-dynamics-365-web-api"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex
