### YamlMime:OData
uid: Microsoft.Dynamics.CRM.RetrieveApplicationRibbonResponse
name: "RetrieveApplicationRibbonResponse"
type: complextype
metadata: 
  title: "Common Data Service and Dynamics 365 Customer Engagement RetrieveApplicationRibbonResponse ComplexType Reference | MicrosoftDocs"
  ms.date: "04/27/2020"
  ms.service: "crm-online"
  ms.topic: "reference"
  ms.assetid: 5b3b1380-f54c-4a6f-98f0-9b99bdf41d18
  author: "KumarVivek"
  ms.author: "kvivek"
  manager: "Annbe"
  meta-description: "Reference information about the Web API RetrieveApplicationRibbonResponse ComplexType."
namespace: Microsoft.Dynamics.CRM
# This complex type doesn't inherit from another complextype.
description: "Contains the response from the RetrieveApplicationRibbon function." 
properties:
  description: "The properties of a complex type contain the structured data of the type."
  property_items:
  - name: CompressedApplicationRibbonXml
    type: Edm.Binary
    nullable: true
    unicode: true
    description: " Contains the data representing the requested ribbon definition."
    iscollection: false
# This complex type doesn't have any navigation properties.
usedby:
  description: "The following use the RetrieveApplicationRibbonResponse ComplexType."
  usedby_items:
  - name: Microsoft.Dynamics.CRM.RetrieveApplicationRibbon
    used_as: ReturnType
# This complex type has no remarks.
href_see_also:
- text: "Use the Common Data Service Web API"
  href: "https://docs.microsoft.com/powerapps/developer/common-data-service/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex
