### YamlMime:OData
uid: Microsoft.Dynamics.CRM.appconfigmaster
name: "appconfigmaster"
type: entitytype
metadata: 
  title: "Microsoft Dynamics 365 Customer Engagement appconfigmaster EntityType Reference | MicrosoftDocs"
  ms.date: "2017-10-02"
  ms.service: "crm-online"
  ms.topic: "reference"
  applies_to: 
  - "Dynamics 365 (online)"
  ms.assetid: 088db9d7-e994-4451-bade-a810f739c2c0
  author: "jimdaly"
  ms.author: "jdaly"
  manager: "jdaly"
  meta-description: "Reference information about the Dynamics 365 Customer Engagement appconfigmaster entitytype."
header: 
  description: "Contains the master list of all properties that can be customized for apps in Dynamics 365. For internal use only."
  entity_set_path: "[organization URI]/api/data/v9.0/appconfigmasters"
  base_type: Microsoft.Dynamics.CRM.crmbaseentity
  display_name: App Config Master
  primary_key: appconfigmasterid
  primary_name_attribute: name
  operations_supported: 
  - GET
namespace: Microsoft.Dynamics.CRM
properties:
  description: "Properties represent fields of data stored in the entity.Some properties are read-only."
  property_items:
    - name: appconfigmasterid
      type: Edm.Guid
      display_name: "AppConfigMasterId"
      description: "System-Populated App Configuration instance identifier."
      iscomputed: false
      isreadonly: true
    - name: configtype
      type: Edm.String
      display_name: "ConfigType"
      description: "Enter the App Configuration and Setting property data type."
      iscomputed: false
      isreadonly: true
    - name: createdon
      type: Edm.DateTimeOffset
      display_name: "Created On"
      description: "Shows the date and time when the record was created. The date and time are displayed in the time zone selected in Microsoft Dynamics CRM options."
      iscomputed: false
      isreadonly: true
    - name: defaultvalue
      type: Edm.String
      display_name: "DefaultValue"
      description: "Enter the default value of the App Configuration and Setting property."
      iscomputed: false
      isreadonly: true
    - name: importsequencenumber
      type: Edm.Int32
      display_name: "Import Sequence Number"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
    - name: isnavigationsetting
      type: Edm.Int32
      display_name: "Is Nagivation Setting"
      description: "Enter whether this App Configuration and Setting is Navigation Setting."
      iscomputed: false
      isreadonly: true
    - name: modifiedon
      type: Edm.DateTimeOffset
      display_name: "Modified On"
      description: "Shows the date and time when the record was last updated. The date and time are displayed in the time zone selected in Microsoft Dynamics CRM options."
      iscomputed: false
      isreadonly: true
    - name: name
      type: Edm.String
      display_name: "Name"
      description: "Enter the name of the App Configuration and Setting property with which this customization will be identified."
      iscomputed: false
      isreadonly: false
    - name: overriddencreatedon
      type: Edm.DateTimeOffset
      display_name: "Record Created On"
      description: "Shows the date and time when the record was migrated. The date and time are displayed in the time zone selected in Microsoft Dynamics CRM options."
      iscomputed: false
      isreadonly: true
    - name: parentappconfigmasterid
      type: Edm.String
      display_name: "Enter the parent of App Configuration customization property."
      description: "ParentAppConfigMasterId"
      iscomputed: false
      isreadonly: true
    - name: validator
      type: Edm.String
      display_name: "Enter the validator configuration xml which will validate against its value when creating AppConfigInstance."
      description: "Validator"
      iscomputed: false
      isreadonly: true
    - name: versionnumber
      type: Edm.Int64
      display_name: ""
      description: ""
      iscomputed: false
      isreadonly: true
lookup_properties:
  description: "Lookup properties are read-only, computed properties which contain entity primary key Edm.Guid data for one or more corresponding single-valued navigation properties. More information: [Lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/web-api-types-operations#lookup-properties) and [Retrieve data about lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/query-data-web-api#retrieve-data-about-lookup-properties)."
  property_items:
  - name: _createdby_value
    single_valued_navigation_property:
    - appconfigmaster_createdby
    description: "Shows who created the record."
  - name: _createdonbehalfby_value
    single_valued_navigation_property:
    - appconfigmaster_createdonbehalfby
    description: "Shows who created the record on behalfÂ of another user."
  - name: _modifiedby_value
    single_valued_navigation_property:
    - appconfigmaster_modifiedby
    description: "Shows who last updated the record."
  - name: _modifiedonbehalfby_value
    single_valued_navigation_property:
    - appconfigmaster_modifiedonbehalfby
    description: "Shows who last updated the record on behalf of another user."
  - name: _organizationid_value
    single_valued_navigation_property:
    - organization_appconfigmaster_appconfigmaster
    description: "System-calculated field for Organization identifier."
single_valued_navigation_properties:
  description: "Single-valued navigation properties represent lookup fields where a single entity can be referenced. Each single-valued navigation property has a corresponding partner collection-valued navigation property on the related entity."
  property_items:
  - name: appconfigmaster_createdby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: systemuser_appconfigmaster_createdby
  - name: appconfigmaster_createdonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: systemuser_appconfigmaster_createdonbehalfby
  - name: appconfigmaster_modifiedby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: systemuser_appconfigmaster_modifiedby
  - name: appconfigmaster_modifiedonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: systemuser_appconfigmaster_modifiedonbehalfby
  - name: organization_appconfigmaster_appconfigmaster
    type: Microsoft.Dynamics.CRM.organization
    partner: organization_appconfigmaster
collection_valued_navigation_properties:
  description: "Collection-valued navigation properties represent collections of entities which may represent either a one-to-many (1:N) or many-to-many (N:N) relationship between the entities."
  property_items:
  - name: appconfigmaster_appconfiginstance
    type: Microsoft.Dynamics.CRM.appconfiginstance
    partner: appconfiginstance_appconfigmaster
# This entity has no derived entities.
# This entity has no operations
solutions:
  description: "The following solutions include the appconfigmaster entity type."
  solution_items:
  - Microsoft.Dynamics.CRM.System
# This entity has no remarks.
href_see_also:
- text: "Use the Microsoft Dynamics CRM Web API"
  href: "https://docs.microsoft.com/dynamics365/customer-engagement/developer/use-microsoft-dynamics-365-web-api"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex