### YamlMime:OData
uid: Microsoft.Dynamics.CRM.appconfiginstance
name: "appconfiginstance"
type: entitytype
metadata: 
  title: "Microsoft Dynamics 365 Customer Engagement appconfiginstance EntityType Reference | MicrosoftDocs"
  ms.date: "2017-09-18"
  ms.service: "crm-online"
  ms.topic: "reference"
  applies_to: 
  - "Dynamics 365 (online)"
  ms.assetid: 2b72cb4f-805c-4823-aeaa-cab034393ff2
  author: "jimdaly"
  ms.author: "jdaly"
  manager: "jdaly"
  meta-description: "Reference information about the Dynamics 365 Customer Engagement appconfiginstance entitytype."
header: 
  description: "Contains a property or a list of properties from the app configuration master list that can be customized for any app in Dynamics 365. For internal use only."
  entity_set_path: "[organization URI]/api/data/v9.0/appconfiginstances"
  base_type: Microsoft.Dynamics.CRM.crmbaseentity
  display_name: App Configuration Instance
  primary_key: appconfiginstanceid
  primary_name_attribute: None
  operations_supported: 
  - POST
  - GET
  - PATCH
  - DELETE
namespace: Microsoft.Dynamics.CRM
properties:
  description: "Properties represent fields of data stored in the entity.Some properties are read-only."
  property_items:
    - name: appconfigidunique
      type: Edm.Guid
      display_name: "App Config ID Unique"
      description: "Enter the App Configuration unique identifier of AppConfig entity for which this customization belongs."
      iscomputed: false
      isreadonly: false
    - name: appconfiginstanceid
      type: Edm.Guid
      display_name: "AppConfig Instance ID"
      description: "System-Populated App Configuration instance identifier."
      iscomputed: false
      isreadonly: true
    - name: appconfiginstanceidunique
      type: Edm.Guid
      display_name: "AppConfigInstanceIdUnique"
      description: "System-populated App Configuration Instance unique identifier."
      iscomputed: false
      isreadonly: false
    - name: componentstate
      type: Edm.Int32
      display_name: "Component State"
      description: "System-Populated Published or UnPublished state of App Configuration Instance."
      iscomputed: false
      isreadonly: true
      options:
        - value: 0
          label: "Published"
        - value: 1
          label: "Unpublished"
        - value: 2
          label: "Deleted"
        - value: 3
          label: "Deleted Unpublished"
    - name: componenttype
      type: Edm.String
      display_name: "Enter the componenet type of the artifact (Form/View etc.) for which customization is to be created."
      description: "ComponentType"
      iscomputed: false
      isreadonly: false
    - name: createdon
      type: Edm.DateTimeOffset
      display_name: "Created On"
      description: "Shows the date and time when the record was created. The date and time are displayed in the time zone selected in Microsoft Dynamics CRM options."
      iscomputed: false
      isreadonly: true
    - name: importsequencenumber
      type: Edm.Int32
      display_name: "Import Sequence Number"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
    - name: introducedversion
      type: Edm.String
      display_name: "Introduced Version"
      description: "Shows the version in which the App Configuration Instance is introduced."
      iscomputed: false
      isreadonly: false
    - name: ismanaged
      type: Edm.Boolean
      display_name: "Shows whether the App Configuration Instance is managed or not."
      description: "Is Managed"
      iscomputed: false
      isreadonly: true
      options:
        - value: 1
          label: "Managed"
        - value: 0
          label: "Unmanaged"
    - name: modifiedon
      type: Edm.DateTimeOffset
      display_name: "Modified On"
      description: "Shows the date and time when the record was last updated. The date and time are displayed in the time zone selected in Microsoft Dynamics CRM options."
      iscomputed: false
      isreadonly: true
    - name: objectid
      type: Edm.Guid
      display_name: "Enter the object identifier for the artifact (Form/View etc.) for which customization is to be created."
      description: "ObjectId"
      iscomputed: false
      isreadonly: false
    - name: overriddencreatedon
      type: Edm.DateTimeOffset
      display_name: "Record Created On"
      description: "Shows the date and time when the record was migrated. The date and time are displayed in the time zone selected in Microsoft Dynamics CRM options."
      iscomputed: false
      isreadonly: true
    - name: overwritetime
      type: Edm.DateTimeOffset
      display_name: "Overwrite Time"
      description: "Shows the last overwrite time for the App Configuration Instance."
      iscomputed: false
      isreadonly: true
    - name: solutionid
      type: Edm.Guid
      display_name: "SolutionId"
      description: "Set the solution idenfitier for associated solution."
      iscomputed: false
      isreadonly: true
    - name: value
      type: Edm.String
      display_name: "Value"
      description: "Enter a value for the customization property that is valid as per the validator XML specified in the app configuration master record."
      iscomputed: false
      isreadonly: false
    - name: versionnumber
      type: Edm.Int64
      display_name: ""
      description: ""
      iscomputed: false
      isreadonly: true
lookup_properties:
  description: "Lookup properties are read-only, computed properties which contain entity primary key Edm.Guid data for one or more corresponding single-valued navigation properties. More information: [Lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/web-api-types-operations#lookup-properties) and [Retrieve data about lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/query-data-web-api#retrieve-data-about-lookup-properties)."
  property_items:
  - name: _appconfigid_value
    single_valued_navigation_property:
    - appconfiginstance_appconfig
    description: "System-calculated App Configuration unique identifier."
  - name: _appconfigmasterid_value
    single_valued_navigation_property:
    - appconfiginstance_appconfigmaster
    description: "System-calculated App Configuration Master identifier."
  - name: _createdby_value
    single_valued_navigation_property:
    - appconfiginstance_createdby
    description: "Shows who created the record."
  - name: _createdonbehalfby_value
    single_valued_navigation_property:
    - appconfiginstance_createdonbehalfby
    description: "Shows who created the record on behalfÂ of another user."
  - name: _modifiedby_value
    single_valued_navigation_property:
    - appconfiginstance_modifiedby
    description: "Shows who last updated the record."
  - name: _modifiedonbehalfby_value
    single_valued_navigation_property:
    - appconfiginstance_modifiedonbehalfby
    description: "Shows who last updated the record on behalf of another user."
  - name: _organizationid_value
    single_valued_navigation_property:
    - organization_appconfiginstance_appconfiginstance
    description: "System-calculated field for Organization identifier."
single_valued_navigation_properties:
  description: "Single-valued navigation properties represent lookup fields where a single entity can be referenced. Each single-valued navigation property has a corresponding partner collection-valued navigation property on the related entity."
  property_items:
  - name: appconfiginstance_appconfig
    type: Microsoft.Dynamics.CRM.appconfig
    partner: appconfig_appconfiginstance
  - name: appconfiginstance_appconfigmaster
    type: Microsoft.Dynamics.CRM.appconfigmaster
    partner: appconfigmaster_appconfiginstance
  - name: appconfiginstance_createdby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: systemuser_appconfiginstance_createdby
  - name: appconfiginstance_createdonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: systemuser_appconfiginstance_createdonbehalfby
  - name: appconfiginstance_modifiedby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: systemuser_appconfiginstance_modifiedby
  - name: appconfiginstance_modifiedonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: systemuser_appconfiginstance_modifiedonbehalfby
  - name: organization_appconfiginstance_appconfiginstance
    type: Microsoft.Dynamics.CRM.organization
    partner: organization_appconfiginstance
# This entity has no collection-valued navigation properties
# This entity has no derived entities.
operations:
  description: "The following operations can be used with the appconfiginstance entity type."
  operation_items:
  - name: Microsoft.Dynamics.CRM.RetrieveUnpublished
    binding_type: "Entity"
  - name: Microsoft.Dynamics.CRM.RetrieveUnpublishedMultiple
    binding_type: "Collection"
solutions:
  description: "The following solutions include the appconfiginstance entity type."
  solution_items:
  - Microsoft.Dynamics.CRM.System
# There are no remarks for this entity.
href_see_also:
- text: "Use the Microsoft Dynamics CRM Web API"
  href: "https://docs.microsoft.com/dynamics365/customer-engagement/developer/use-microsoft-dynamics-365-web-api"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex