### YamlMime:OData
uid: Microsoft.Dynamics.CRM.appconfig
name: "appconfig"
type: entitytype
metadata: 
  title: "Microsoft Dynamics 365 Customer Engagement appconfig EntityType Reference | MicrosoftDocs"
  ms.date: "2017-09-21"
  ms.service: "crm-online"
  ms.topic: "reference"
  applies_to: 
  - "Dynamics 365 (online)"
  ms.assetid: 4e3e3100-c04a-4725-8262-93db8b34d1cb
  author: "jimdaly"
  ms.author: "jdaly"
  manager: "jdaly"
  meta-description: "Reference information about the Dynamics 365 Customer Engagement appconfig entitytype."
header: 
  description: "Contains a mapping between an app configuration instance and an app, which defines the properties that can be customized for the app. Optionally, also contains navigation setting for an app. For internal use only."
  entity_set_path: "[organization URI]/api/data/v9.0/appconfigs"
  base_type: Microsoft.Dynamics.CRM.crmbaseentity
  display_name: App Configuration
  primary_key: appconfigid
  primary_name_attribute: None
  operations_supported: 
  - POST
  - GET
  - PATCH
  - DELETE
namespace: Microsoft.Dynamics.CRM
properties:
  description: "Properties represent fields of data stored in the entity.Some properties are read-only."
  property_items:
    - name: appconfigid
      type: Edm.Guid
      display_name: "App Config ID"
      description: "System-populated app configuration ID."
      iscomputed: false
      isreadonly: true
    - name: appconfigidunique
      type: Edm.Guid
      display_name: "App Config ID Unique"
      description: "System-populated app configuration unique ID."
      iscomputed: false
      isreadonly: false
    - name: appconfigimportxml
      type: Edm.String
      display_name: ""
      description: "The App Config diff computed for managed solutions containing the AppConfig entity. For internal use only."
      iscomputed: false
      isreadonly: false
    - name: componentstate
      type: Edm.Int32
      display_name: "Component State"
      description: "For internal use only"
      iscomputed: false
      isreadonly: true
      options:
        - value: 0
          label: "Published"
        - value: 1
          label: "Unpublished"
        - value: 2
          label: "Deleted"
        - value: 3
          label: "Deleted Unpublished"
    - name: createdon
      type: Edm.DateTimeOffset
      display_name: "Created On"
      description: "Shows the date and time when the record was created. The date and time are displayed in the time zone selected in Microsoft Dynamics CRM options."
      iscomputed: false
      isreadonly: true
    - name: importsequencenumber
      type: Edm.Int32
      display_name: "Import Sequence Number"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
    - name: introducedversion
      type: Edm.String
      display_name: "Introduced Version"
      description: "Version in which the similarity rule is introduced."
      iscomputed: false
      isreadonly: false
    - name: ismanaged
      type: Edm.Boolean
      display_name: "Indicates whether this is part of a managed solution."
      description: "Is Managed"
      iscomputed: false
      isreadonly: true
      options:
        - value: 1
          label: "Managed"
        - value: 0
          label: "Unmanaged"
    - name: modifiedon
      type: Edm.DateTimeOffset
      display_name: "Modified On"
      description: "Shows the date and time when the record was last updated. The date and time are displayed in the time zone selected in Microsoft Dynamics CRM options."
      iscomputed: false
      isreadonly: true
    - name: overriddencreatedon
      type: Edm.DateTimeOffset
      display_name: "Record Created On"
      description: "Shows the date and time when the record was migrated. The date and time are displayed in the time zone selected in Microsoft Dynamics CRM options."
      iscomputed: false
      isreadonly: true
    - name: overwritetime
      type: Edm.DateTimeOffset
      display_name: "Overwrite Time"
      description: "Internal use only"
      iscomputed: false
      isreadonly: true
    - name: solutionid
      type: Edm.Guid
      display_name: "Solution"
      description: "Unique identifier of the associated solution."
      iscomputed: false
      isreadonly: true
    - name: statecode
      type: Edm.Int32
      display_name: "Status"
      description: "Shows whether the app configuration is Active or Inactive. Inactive records are read-only and can't be edited unless they are reactivated."
      iscomputed: false
      isreadonly: false
      options:
        - value: 0
          label: "Active"
        - value: 1
          label: "Inactive"
    - name: statuscode
      type: Edm.Int32
      display_name: "Status Reason"
      description: "Select the status."
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Active"
        - value: 2
          label: "Inactive"
    - name: versionnumber
      type: Edm.Int64
      display_name: ""
      description: ""
      iscomputed: false
      isreadonly: true
lookup_properties:
  description: "Lookup properties are read-only, computed properties which contain entity primary key Edm.Guid data for one or more corresponding single-valued navigation properties. More information: [Lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/web-api-types-operations#lookup-properties) and [Retrieve data about lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/query-data-web-api#retrieve-data-about-lookup-properties)."
  property_items:
  - name: _appmoduleid_value
    single_valued_navigation_property:
    - appmodule_appconfig
    description: "Choose the app module to associate with the app configuration."
  - name: _createdby_value
    single_valued_navigation_property:
    - appconfig_createdby
    description: "Shows who created the record."
  - name: _createdonbehalfby_value
    single_valued_navigation_property:
    - appconfig_createdonbehalfby
    description: "Shows who created the record on behalfÂ of another user."
  - name: _modifiedby_value
    single_valued_navigation_property:
    - appconfig_modifiedby
    description: "Shows who last updated the record."
  - name: _modifiedonbehalfby_value
    single_valued_navigation_property:
    - appconfig_modifiedonbehalfby
    description: "Shows who last updated the record on behalf of another user."
  - name: _organizationid_value
    single_valued_navigation_property:
    - organization_appconfig
    description: "Unique identifier for the organization."
single_valued_navigation_properties:
  description: "Single-valued navigation properties represent lookup fields where a single entity can be referenced. Each single-valued navigation property has a corresponding partner collection-valued navigation property on the related entity."
  property_items:
  - name: appconfig_createdby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: systemuser_appconfig_createdby
  - name: appconfig_createdonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: systemuser_appconfig_createdonbehalfby
  - name: appconfig_modifiedby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: systemuser_appconfig_modifiedby
  - name: appconfig_modifiedonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: systemuser_appconfig_modifiedonbehalfby
  - name: appmodule_appconfig
    type: Microsoft.Dynamics.CRM.appmodule
    partner: appmodule_appconfig
  - name: organization_appconfig
    type: Microsoft.Dynamics.CRM.organization
    partner: organization_appconfig
collection_valued_navigation_properties:
  description: "Collection-valued navigation properties represent collections of entities which may represent either a one-to-many (1:N) or many-to-many (N:N) relationship between the entities."
  property_items:
  - name: appconfig_appconfiginstance
    type: Microsoft.Dynamics.CRM.appconfiginstance
    partner: appconfiginstance_appconfig
  - name: appconfig_navigationsetting
    type: Microsoft.Dynamics.CRM.navigationsetting
    partner: navigationsetting_appconfig
# This entity has no derived entities.
operations:
  description: "The following operations can be used with the appconfig entity type."
  operation_items:
  - name: Microsoft.Dynamics.CRM.RetrieveUnpublished
    binding_type: "Entity"
  - name: Microsoft.Dynamics.CRM.RetrieveUnpublishedMultiple
    binding_type: "Collection"
solutions:
  description: "The following solutions include the appconfig entity type."
  solution_items:
  - Microsoft.Dynamics.CRM.System
# There are no remarks for this entity.
href_see_also:
- text: "Use the Microsoft Dynamics CRM Web API"
  href: "https://docs.microsoft.com/dynamics365/customer-engagement/developer/use-microsoft-dynamics-365-web-api"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex