### YamlMime:OData
uid: Microsoft.Dynamics.CRM.msdyn_wallsavedqueryusersettings
name: "msdyn_wallsavedqueryusersettings"
type: entitytype
metadata: 
  title: "Microsoft Dynamics 365 Customer Engagement msdyn_wallsavedqueryusersettings EntityType Reference | MicrosoftDocs"
  ms.date: "2017-09-18"
  ms.service: "crm-online"
  ms.topic: "reference"
  applies_to: 
  - "Dynamics 365 (online)"
  ms.assetid: 2c5d762b-64ff-4232-9378-6340ed5d05e9
  author: "jimdaly"
  ms.author: "jdaly"
  manager: "jdaly"
  meta-description: "Reference information about the Dynamics 365 Customer Engagement msdyn_wallsavedqueryusersettings entitytype."
header: 
  description: "Contains user personalization information regarding which of the administrator’s selected views to display on a user’s personal wall."
  entity_set_path: "[organization URI]/api/data/v9.0/msdyn_wallsavedqueryusersettingses"
  base_type: Microsoft.Dynamics.CRM.crmbaseentity
  display_name: Filter
  primary_key: msdyn_wallsavedqueryusersettingsid
  primary_name_attribute: msdyn_entityname
  operations_supported: 
  - POST
  - GET
  - PATCH
  - DELETE
namespace: Microsoft.Dynamics.CRM
properties:
  description: "Properties represent fields of data stored in the entity.Some properties are read-only."
  property_items:
    - name: createdon
      type: Edm.DateTimeOffset
      display_name: "Created On"
      description: "Date and time when the record was created."
      iscomputed: false
      isreadonly: true
    - name: importsequencenumber
      type: Edm.Int32
      display_name: "Import Sequence Number"
      description: "Sequence number of the import that created this record."
      iscomputed: false
      isreadonly: false
    - name: modifiedon
      type: Edm.DateTimeOffset
      display_name: "Modified On"
      description: "Date and time when the record was modified."
      iscomputed: false
      isreadonly: true
    - name: msdyn_data
      type: Edm.String
      display_name: "Data"
      description: "XML blob that stores personalization data for the user."
      iscomputed: false
      isreadonly: false
    - name: msdyn_default
      type: Edm.Int32
      display_name: "Default"
      description: "Indicates that view is selected by default if value is greater than 0. Also contains information which specific filter is applied."
      iscomputed: false
      isreadonly: false
    - name: msdyn_entitydisplayname
      type: Edm.String
      display_name: "Entity Display Name"
      description: "Display name of the entity to which the corresponding views belong."
      iscomputed: false
      isreadonly: false
    - name: msdyn_entityname
      type: Edm.String
      display_name: "Entity Name"
      description: "Name of the entity to which the corresponding views belong."
      iscomputed: false
      isreadonly: false
    - name: msdyn_includewallinresponse
      type: Edm.Boolean
      display_name: "Include Wall in response"
      description: "Indicates that wall should be included in response to avoid roundtrips to server"
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Yes"
        - value: 0
          label: "No"
    - name: msdyn_isfollowing
      type: Edm.Boolean
      display_name: "Is Following"
      description: "Indicates that corresponding view is following view"
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Yes"
        - value: 0
          label: "No"
    - name: msdyn_isvirtual
      type: Edm.Boolean
      display_name: "Is Virtual"
      description: "Indicates that the record is virtual"
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Yes"
        - value: 0
          label: "No"
    - name: msdyn_isvisible
      type: Edm.Boolean
      display_name: "Display on the wall"
      description: "Information that indicates whether the corresponding view should be displayed on the personal wall for this user."
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Shown"
        - value: 0
          label: "Hidden"
    - name: msdyn_isvisiblebit
      type: Edm.Int32
      display_name: "Is Visible bit"
      description: "For internal use only."
      iscomputed: false
      isreadonly: false
    - name: msdyn_otc
      type: Edm.Int32
      display_name: "Entity Type"
      description: "Virtual column which contains entity type code for the entities returned by corresponding savedquery"
      iscomputed: false
      isreadonly: false
    - name: msdyn_savedqueryname
      type: Edm.String
      display_name: "View Name"
      description: "Name of the corresponding view."
      iscomputed: false
      isreadonly: false
    - name: msdyn_sortorder
      type: Edm.Int32
      display_name: "Sort Order"
      description: "Sort order to be used when displaying the filter on the user’s personal wall."
      iscomputed: false
      isreadonly: false
    - name: msdyn_type
      type: Edm.Int32
      display_name: "Type"
      description: "Reserved to support different view types. Currently not used."
      iscomputed: false
      isreadonly: false
    - name: msdyn_wallsavedqueryusersettingsid
      type: Edm.Guid
      display_name: "Filter"
      description: "Unique identifier for entity instances"
      iscomputed: false
      isreadonly: false
    - name: overriddencreatedon
      type: Edm.DateTimeOffset
      display_name: "Record Created On"
      description: "Date and time that the record was migrated."
      iscomputed: false
      isreadonly: false
    - name: statecode
      type: Edm.Int32
      display_name: "Status"
      description: "Status of the Wall View User Setting"
      iscomputed: false
      isreadonly: false
      options:
        - value: 0
          label: "Active"
        - value: 1
          label: "Inactive"
    - name: statuscode
      type: Edm.Int32
      display_name: "Status Reason"
      description: "Reason for the status of the Wall View User Setting"
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Active"
        - value: 2
          label: "Inactive"
    - name: timezoneruleversionnumber
      type: Edm.Int32
      display_name: "Time Zone Rule Version Number"
      description: "For internal use only."
      iscomputed: false
      isreadonly: false
    - name: utcconversiontimezonecode
      type: Edm.Int32
      display_name: "UTC Conversion Time Zone Code"
      description: "Time zone code that was in use when the record was created."
      iscomputed: false
      isreadonly: false
    - name: versionnumber
      type: Edm.Int64
      display_name: "Version Number"
      description: "Version Number"
      iscomputed: false
      isreadonly: true
lookup_properties:
  description: "Lookup properties are read-only, computed properties which contain entity primary key Edm.Guid data for one or more corresponding single-valued navigation properties. More information: [Lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/web-api-types-operations#lookup-properties) and [Retrieve data about lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/query-data-web-api#retrieve-data-about-lookup-properties)."
  property_items:
  - name: _createdby_value
    single_valued_navigation_property:
    - createdby
    description: "Unique identifier of the user who created the record."
  - name: _createdonbehalfby_value
    single_valued_navigation_property:
    - createdonbehalfby
    description: "Unique identifier of the delegate user who created the record."
  - name: _modifiedby_value
    single_valued_navigation_property:
    - modifiedby
    description: "Unique identifier of the user who modified the record."
  - name: _modifiedonbehalfby_value
    single_valued_navigation_property:
    - modifiedonbehalfby
    description: "Unique identifier of the delegate user who modified the record."
  - name: _msdyn_userid_value
    single_valued_navigation_property:
    - msdyn_userid
    description: "Unique identifier for User associated with Wall View User Setting."
  - name: _msdyn_wallsavedqueryid_value
    single_valued_navigation_property:
    - msdyn_wallsavedqueryid
    description: "Unique identifier for Wall View associated with Wall View User Setting."
  - name: _ownerid_value
    single_valued_navigation_property:
    - ownerid
    description: "Owner Id"
  - name: _owningbusinessunit_value
    single_valued_navigation_property:
    - owningbusinessunit
    description: "Unique identifier for the business unit that owns the record"
  - name: _owningteam_value
    single_valued_navigation_property:
    - owningteam
    description: "Unique identifier for the team that owns the record."
  - name: _owninguser_value
    single_valued_navigation_property:
    - owninguser
    description: "Unique identifier for the user that owns the record."
single_valued_navigation_properties:
  description: "Single-valued navigation properties represent lookup fields where a single entity can be referenced. Each single-valued navigation property has a corresponding partner collection-valued navigation property on the related entity."
  property_items:
  - name: createdby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_wallsavedqueryusersettings_createdby
  - name: createdonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_wallsavedqueryusersettings_createdonbehalfby
  - name: modifiedby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_wallsavedqueryusersettings_modifiedby
  - name: modifiedonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_wallsavedqueryusersettings_modifiedonbehalfby
  - name: msdyn_userid
    type: Microsoft.Dynamics.CRM.systemuser
    partner: msdyn_systemuser_wallsavedqueryusersettings_userid
  - name: msdyn_wallsavedqueryid
    type: Microsoft.Dynamics.CRM.msdyn_wallsavedquery
    partner: msdyn_wallsavedquery_wallsavedqueryusersettings
  - name: ownerid
    type: Microsoft.Dynamics.CRM.principal
    partner: owner_msdyn_wallsavedqueryusersettings
  - name: owningbusinessunit
    type: Microsoft.Dynamics.CRM.businessunit
    partner: business_unit_msdyn_wallsavedqueryusersettings
  - name: owningteam
    type: Microsoft.Dynamics.CRM.team
    partner: team_msdyn_wallsavedqueryusersettings
  - name: owninguser
    type: Microsoft.Dynamics.CRM.systemuser
    partner: user_msdyn_wallsavedqueryusersettings
collection_valued_navigation_properties:
  description: "Collection-valued navigation properties represent collections of entities which may represent either a one-to-many (1:N) or many-to-many (N:N) relationship between the entities."
  property_items:
  - name: msdyn_wallsavedqueryusersettings_AsyncOperations
    type: Microsoft.Dynamics.CRM.asyncoperation
    partner: regardingobjectid_msdyn_wallsavedqueryusersettings
  - name: msdyn_wallsavedqueryusersettings_BulkDeleteFailures
    type: Microsoft.Dynamics.CRM.bulkdeletefailure
    partner: regardingobjectid_msdyn_wallsavedqueryusersettings
  - name: msdyn_wallsavedqueryusersettings_MailboxTrackingFolders
    type: Microsoft.Dynamics.CRM.mailboxtrackingfolder
    partner: regardingobjectid_msdyn_wallsavedqueryusersettings
  - name: msdyn_wallsavedqueryusersettings_PrincipalObjectAttributeAccesses
    type: Microsoft.Dynamics.CRM.principalobjectattributeaccess
    partner: objectid_msdyn_wallsavedqueryusersettings
  - name: msdyn_wallsavedqueryusersettings_ProcessSession
    type: Microsoft.Dynamics.CRM.processsession
    partner: regardingobjectid_msdyn_wallsavedqueryusersettings
  - name: msdyn_wallsavedqueryusersettings_SyncErrors
    type: Microsoft.Dynamics.CRM.syncerror
    partner: regardingobjectid_msdyn_wallsavedqueryusersettings
# This entity has no derived entities.
operations:
  description: "The following operations can be used with the msdyn_wallsavedqueryusersettings entity type."
  operation_items:
  - name: Microsoft.Dynamics.CRM.GrantAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.IsValidStateTransition
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.ModifyAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.RetrievePrincipalAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.RetrieveSharedPrincipalsAndAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.RevokeAccess
    binding_type: "Not Bound"
solutions:
  description: "The following solutions include the msdyn_wallsavedqueryusersettings entity type."
  solution_items:
  - Microsoft.Dynamics.CRM.ActivityFeedsCore
# There are no remarks for this entity.
href_see_also:
- text: "Use the Microsoft Dynamics CRM Web API"
  href: "https://docs.microsoft.com/dynamics365/customer-engagement/developer/use-microsoft-dynamics-365-web-api"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex