### YamlMime:OData
uid: Microsoft.Dynamics.CRM.service
name: "service"
type: entitytype
metadata: 
  title: "Common Data Service and Dynamics 365 Customer Engagement service EntityType Reference | MicrosoftDocs"
  ms.date: "05/03/2020"
  ms.service: "crm-online"
  ms.topic: "reference"
  ms.assetid: 4c60a0e6-bbac-4f12-a4cf-e2f9da658a99
  author: "KumarVivek"
  ms.author: "kvivek"
  manager: "Annbe"
  meta-description: "Reference information about the service entitytype."
description: "Activity that represents work done to satisfy a customer's need."
header:
  entity_set_path: "[organization URI]/api/data/v9.0/services"
  base_type: Microsoft.Dynamics.CRM.crmbaseentity
  display_name: Service
  primary_key: serviceid
  primary_name_attribute: name
  operations_supported:
  - POST
  - GET
  - PATCH
  - DELETE
namespace: Microsoft.Dynamics.CRM
properties:
  description: "Properties represent fields of data stored in the entity.Some properties are read-only."
  property_items:
    - name: anchoroffset
      type: Edm.Int32
      display_name: "Anchor Offset"
      description: "Used in conjunction with granularity to describes when services can be performed in relation to midnight on a given day."
      iscomputed: false
      isreadonly: false
    - name: calendarid
      type: Edm.Guid
      display_name: "Calendar"
      description: "Unique identifier of the calendar."
      iscomputed: false
      isreadonly: false
    - name: createdon
      type: Edm.DateTimeOffset
      display_name: "Created On"
      description: "Date and time when the service was created."
      iscomputed: false
      isreadonly: true
    - name: description
      type: Edm.String
      display_name: "Description"
      description: "Description of activity that represents work done to satisfy a customer's need."
      iscomputed: false
      isreadonly: false
    - name: duration
      type: Edm.Int32
      display_name: "Duration"
      description: "Duration of the service."
      iscomputed: false
      isreadonly: false
    - name: granularity
      type: Edm.String
      display_name: "Granularity"
      description: "Describes how often the service is performed."
      iscomputed: false
      isreadonly: false
    - name: importsequencenumber
      type: Edm.Int32
      display_name: "Import Sequence Number"
      description: "Sequence number of the import that created this record."
      iscomputed: false
      isreadonly: false
    - name: initialstatuscode
      type: Edm.Int32
      display_name: "Initial Status Reason"
      description: "Initial status reason for the service activity."
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Requested"
        - value: 2
          label: "Tentative"
        - value: 3
          label: "Pending"
        - value: 4
          label: "Reserved"
        - value: 6
          label: "In Progress"
        - value: 7
          label: "Arrived"
        - value: 8
          label: "Completed"
        - value: 9
          label: "Canceled"
        - value: 10
          label: "No Show"
    - name: isschedulable
      type: Edm.Boolean
      display_name: "Status"
      description: "Information about whether the service can be scheduled."
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Active"
        - value: 0
          label: "Inactive"
    - name: isvisible
      type: Edm.Boolean
      display_name: "Is Visible"
      description: "Information about whether the service is visible to users."
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Yes"
        - value: 0
          label: "No"
    - name: modifiedon
      type: Edm.DateTimeOffset
      display_name: "Modified On"
      description: "Date and time when the service was last modified."
      iscomputed: false
      isreadonly: true
    - name: name
      type: Edm.String
      display_name: "Name"
      description: "Name of the service."
      iscomputed: false
      isreadonly: false
    - name: overriddencreatedon
      type: Edm.DateTimeOffset
      display_name: "Record Created On"
      description: "Date and time that the record was migrated."
      iscomputed: false
      isreadonly: false
    - name: serviceid
      type: Edm.Guid
      display_name: "Service"
      description: "Unique identifier of the associated service."
      iscomputed: false
      isreadonly: false
    - name: showresources
      type: Edm.Boolean
      display_name: "Show Resources"
      description: "For internal use only."
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Yes"
        - value: 0
          label: "No"
    - name: timezoneruleversionnumber
      type: Edm.Int32
      display_name: "Time Zone Rule Version Number"
      description: "For internal use only."
      iscomputed: false
      isreadonly: false
    - name: utcconversiontimezonecode
      type: Edm.Int32
      display_name: "UTC Conversion Time Zone Code"
      description: "Time zone code that was in use when the record was created."
      iscomputed: false
      isreadonly: false
    - name: versionnumber
      type: Edm.Int64
      display_name: "Version Number"
      description: "Version Number"
      iscomputed: false
      isreadonly: true
lookup_properties:
  description: "Lookup properties are read-only, computed properties which contain entity primary key Edm.Guid data for one or more corresponding single-valued navigation properties. More information: [Lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/web-api-types-operations#lookup-properties) and [Retrieve data about lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/query-data-web-api#retrieve-data-about-lookup-properties)."
  property_items:
  - name: _createdby_value
    single_valued_navigation_property:
    - createdby
    description: "Unique identifier of the user who created the service."
  - name: _createdonbehalfby_value
    single_valued_navigation_property:
    - createdonbehalfby
    description: "Unique identifier of the delegate user who created the service."
  - name: _modifiedby_value
    single_valued_navigation_property:
    - modifiedby
    description: "Unique identifier of the user who last modified the service."
  - name: _modifiedonbehalfby_value
    single_valued_navigation_property:
    - modifiedonbehalfby
    description: "Unique identifier of the delegate user who last modified the service."
  - name: _organizationid_value
    single_valued_navigation_property:
    - organizationid
    description: "Unique identifier for the organization"
  - name: _resourcespecid_value
    single_valued_navigation_property:
    - resourcespecid
    description: "Unique identifier of the resource specification with which the service is associated."
  - name: _strategyid_value
    single_valued_navigation_property:
    - strategyid
    description: "Value that is taken from PluginTypeId in the Plugin Type record for the scheduling strategy. This is the ID of the scheduling strategy plug-in associated with the service."
single_valued_navigation_properties:
  description: "Single-valued navigation properties represent lookup fields where a single entity can be referenced. Each single-valued navigation property has a corresponding partner collection-valued navigation property on the related entity."
  property_items:
  - name: calendarid_calendar
    type: Microsoft.Dynamics.CRM.calendar
    partner: calendar_services
  - name: createdby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_service_createdby
  - name: createdonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_service_createdonbehalfby
  - name: modifiedby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_service_modifiedby
  - name: modifiedonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_service_modifiedonbehalfby
  - name: organizationid
    type: Microsoft.Dynamics.CRM.organization
    partner: organization_services
  - name: resourcespecid
    type: Microsoft.Dynamics.CRM.resourcespec
    partner: resource_spec_services
  - name: strategyid
    type: Microsoft.Dynamics.CRM.plugintype
    partner: plugin_type_service
collection_valued_navigation_properties:
  description: "Collection-valued navigation properties represent collections of entities which may represent either a one-to-many (1:N) or many-to-many (N:N) relationship between the entities."
  property_items:
  - name: msdyn_approval_service_serviceid
    type: Microsoft.Dynamics.CRM.msdyn_approval
    partner: serviceid_msdyn_approval
  - name: msdyn_bookingalert_service_serviceid
    type: Microsoft.Dynamics.CRM.msdyn_bookingalert
    partner: serviceid_msdyn_bookingalert
  - name: service_accounts
    type: Microsoft.Dynamics.CRM.account
    partner: preferredserviceid
  - name: service_activity_pointers
    type: Microsoft.Dynamics.CRM.activitypointer
    partner: serviceid
  - name: Service_Annotation
    type: Microsoft.Dynamics.CRM.annotation
    partner: objectid_service
  - name: service_appointments
    type: Microsoft.Dynamics.CRM.appointment
    partner: serviceid_appointment
  - name: Service_AsyncOperations
    type: Microsoft.Dynamics.CRM.asyncoperation
    partner: regardingobjectid_service
  - name: Service_BulkDeleteFailures
    type: Microsoft.Dynamics.CRM.bulkdeletefailure
    partner: regardingobjectid_service
  - name: service_calendar_rules
    type: Microsoft.Dynamics.CRM.calendarrule
    partner: serviceid
  - name: service_contacts
    type: Microsoft.Dynamics.CRM.contact
    partner: preferredserviceid
  - name: Service_DuplicateBaseRecord
    type: Microsoft.Dynamics.CRM.duplicaterecord
    partner: baserecordid_service
  - name: Service_DuplicateMatchingRecord
    type: Microsoft.Dynamics.CRM.duplicaterecord
    partner: duplicaterecordid_service
  - name: service_emails
    type: Microsoft.Dynamics.CRM.email
    partner: serviceid_email
  - name: service_faxes
    type: Microsoft.Dynamics.CRM.fax
    partner: serviceid_fax
  - name: service_incidentresolutions
    type: Microsoft.Dynamics.CRM.incidentresolution
    partner: serviceid_incidentresolution
  - name: service_letters
    type: Microsoft.Dynamics.CRM.letter
    partner: serviceid_letter
  - name: service_MailboxTrackingFolders
    type: Microsoft.Dynamics.CRM.mailboxtrackingfolder
    partner: regardingobjectid_service
  - name: service_opportunityclose
    type: Microsoft.Dynamics.CRM.opportunityclose
    partner: serviceid_opportunityclose
  - name: service_orderclose
    type: Microsoft.Dynamics.CRM.orderclose
    partner: serviceid_orderclose
  - name: service_phonecalls
    type: Microsoft.Dynamics.CRM.phonecall
    partner: serviceid_phonecall
  - name: service_PrincipalObjectAttributeAccesses
    type: Microsoft.Dynamics.CRM.principalobjectattributeaccess
    partner: objectid_service
  - name: Service_ProcessSessions
    type: Microsoft.Dynamics.CRM.processsession
    partner: regardingobjectid_service
  - name: service_quoteclose
    type: Microsoft.Dynamics.CRM.quoteclose
    partner: serviceid_quoteclose
  - name: service_recurringappointmentmasters
    type: Microsoft.Dynamics.CRM.recurringappointmentmaster
    partner: serviceid_recurringappointmentmaster
  - name: service_service_appointments
    type: Microsoft.Dynamics.CRM.serviceappointment
    partner: serviceid_serviceappointment
  - name: service_socialactivities
    type: Microsoft.Dynamics.CRM.socialactivity
    partner: serviceid_socialactivity
  - name: Service_SyncErrors
    type: Microsoft.Dynamics.CRM.syncerror
    partner: regardingobjectid_service_syncerror
  - name: service_tasks
    type: Microsoft.Dynamics.CRM.task
    partner: serviceid_task
# This entity has no derived entities.
operations:
  description: "The following operations can be used with the service entity type."
  operation_items:
  - name: Microsoft.Dynamics.CRM.RetrieveByResourcesService
    binding_type: "Not Bound"
solutions:
  description: "The following solutions include the service entity type."
  solution_items:
  - type: Microsoft.Dynamics.CRM.msdynce_Service
    description: "Dynamics 365 workload for service."
  - type: Microsoft.Dynamics.CRM.msdynce_ServicePatch201911
    description: "Dynamics 365 workload for service."
# This entity has no remarks.
href_see_also:
- text: "Use the Common Data Service Web API"
  href: "https://docs.microsoft.com/powerapps/developer/common-data-service/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex