### YamlMime:OData
uid: Microsoft.Dynamics.CRM.GetDistinctValuesImportFile
name: "GetDistinctValuesImportFile"
type: function
metadata: 
  title: "Microsoft Dynamics 365 Customer Engagement GetDistinctValuesImportFile Function Reference | MicrosoftDocs"
  ms.date: "10/20/2017"
  ms.service: "crm-online"
  ms.topic: "reference"
  applies_to: 
  - "Dynamics 365 (online)"
  ms.assetid: 5f60e8ad-b47a-49fc-87a4-ba001c881078
  author: "jimdaly"
  ms.author: "jdaly"
  manager: "jdaly"
  meta-description: "Reference information about the Dynamics 365 Customer Engagement GetDistinctValuesImportFile Function."
namespace: Microsoft.Dynamics.CRM
description: "Retrieves distinct values from the parse table for a column in the source file that contains list values.  "
iscomposable: false
bound_entities:
  description: "Bound functions are invoked by appending the function name to the URI representing an entity or collection."
  bound_entity_items:
  - entity_type: Microsoft.Dynamics.CRM.importfile
    binding_type: entity
parameters:
  description: "Parameters allow for data to be passed to the function."
  parameter_items:
  - name: columnNumber
    type: Edm.Int32
    nullable: false
    unicode: true
    description: "A column number in the CSV, XML Spreadsheet 2003 (.xml), or text source file for which the distinct values are returned. Required. "
  - name: pageNumber
    type: Edm.Int32
    nullable: false
    unicode: true
    description: "The page number in the source file. Required. "
  - name: recordsPerPage
    type: Edm.Int32
    nullable: false
    unicode: true
    description: "The number of data records per page in the source file. Required.  "
return_type:
  description: "The GetDistinctValuesImportFile function returns the following value."
  type: Microsoft.Dynamics.CRM.GetDistinctValuesImportFileResponse
  iscollection: false
  nullable: false
# This function no specific entities for this function identified.
# This function has no remarks.
href_see_also:
- text: "Use the Dynamics 365 Customer Engagement Web API"
  href: "https://docs.microsoft.com/dynamics365/customer-engagement/developer/use-microsoft-dynamics-365-web-api"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex