### YamlMime:OData
uid: Microsoft.Dynamics.CRM.RetrieveDeploymentLicenseType
name: "RetrieveDeploymentLicenseType"
type: function
metadata: 
  title: "Microsoft Dynamics 365 Customer Engagement RetrieveDeploymentLicenseType Function Reference | MicrosoftDocs"
  ms.date: "10/20/2017"
  ms.service: "crm-online"
  ms.topic: "reference"
  applies_to: 
  - "Dynamics 365 (online)"
  ms.assetid: 1944adce-7d01-4a6c-bc44-1d0613310af6
  author: "jimdaly"
  ms.author: "jdaly"
  manager: "jdaly"
  meta-description: "Reference information about the Dynamics 365 Customer Engagement RetrieveDeploymentLicenseType Function."
namespace: Microsoft.Dynamics.CRM
description: "Retrieves the type of license for a deployment of Microsoft Dynamics 365.  "
iscomposable: false
# This function is not bound to any entities.
isbound: false
# This function has no parameters.
hasparameters: false
return_type:
  description: "The RetrieveDeploymentLicenseType function returns the following value."
  type: Microsoft.Dynamics.CRM.RetrieveDeploymentLicenseTypeResponse
  iscollection: false
  nullable: false
  description: "Retrieves the type of license for a deployment of Microsoft Dynamics 365.  "
# This function no specific entities for this function identified.
# This function has no remarks.
href_see_also:
- text: "Use the Microsoft Dynamics CRM Web API"
  href: "https://docs.microsoft.com/dynamics365/customer-engagement/developer/use-microsoft-dynamics-365-web-api"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex